[terminal.themes.catppuccin-mocha]
"theme_default"                                   = { fg = "$text",     bg = "$base",     attrs = "Default" }
"error_message"                                   = { fg = "$red",      bg = "theme_default", attrs = "theme_default" }
"text.normal"                                     = { fg = "$text",     bg = "$base",     attrs = "Default" }
"text.unfocused"                                  = { fg = "$subtext0", bg = "theme_default", attrs = "Dim" }
"text.error"                                      = { fg = "$red",      bg = "theme_default", attrs = "theme_default" }
"text.highlight"                                  = { fg = "$base",     bg = "$blue",     attrs = "theme_default" }
"highlight"                                       = { fg = "$base",     bg = "$text",     attrs = "Bold" }
"status.bar"                                      = { fg = "$base",     bg = "$blue",     attrs = "Bold" }
"status.command_bar"                              = { fg = "$base",     bg = "$mauve",    attrs = "theme_default" }
"status.history"                                  = { fg = "$peach",    bg = "$surface1", attrs = "theme_default" }
"status.history.hints"                            = { fg = "$base",     bg = "status.command_bar", attrs = "theme_default" }
"status.notification"                             = { fg = "$green",    bg = "theme_default", attrs = "theme_default" }
"tab.focused"                                     = { fg = "$blue",     bg = "$surface0", attrs = "Bold" }
"tab.unfocused"                                   = { fg = "$subtext0", bg = "$mantle",   attrs = "theme_default" }
"tab.bar"                                         = { fg = "$text",     bg = "$mantle",   attrs = "theme_default" }
"widgets.list.header"                             = { fg = "$base",     bg = "$blue",     attrs = "Bold" }
"widgets.form.label"                              = { fg = "$text",     bg = "theme_default", attrs = "Bold" }
"widgets.form.field"                              = { fg = "$text",     bg = "$surface0", attrs = "theme_default" }
"widgets.form.highlighted"                        = { fg = "$base",     bg = "$lavender", attrs = "theme_default" }
"widgets.options.highlighted"                     = { fg = "$base",     bg = "$blue",     attrs = "theme_default" }
"mail.sidebar"                                    = { fg = "$subtext1", bg = "$mantle",   attrs = "theme_default" }
"mail.sidebar_divider"                            = { fg = "$surface1", bg = "$mantle",   attrs = "theme_default" }
"mail.sidebar_account_name"                       = { fg = "$lavender", bg = "$mantle",   attrs = "Bold" }
"mail.sidebar_unread_count"                       = { fg = "$peach",    bg = "$mantle",   attrs = "theme_default" }
"mail.sidebar_index"                              = { fg = "$overlay1", bg = "$mantle",   attrs = "theme_default" }
"mail.sidebar_highlighted"                        = { fg = "$base",     bg = "$blue",     attrs = "theme_default" }
"mail.sidebar_highlighted_unread_count"           = { fg = "$base",     bg = "$blue",     attrs = "theme_default" }
"mail.sidebar_highlighted_index"                  = { fg = "$base",     bg = "$blue",     attrs = "theme_default" }
"mail.sidebar_highlighted_account"                = { fg = "$base",     bg = "$lavender", attrs = "theme_default" }
"mail.sidebar_highlighted_account_name"           = { fg = "$base",     bg = "$lavender", attrs = "Bold" }
"mail.sidebar_highlighted_account_unread_count"   = { fg = "$base",     bg = "$lavender", attrs = "theme_default" }
"mail.sidebar_highlighted_account_index"          = { fg = "$base",     bg = "$lavender", attrs = "theme_default" }
"mail.view.divider"                               = { fg = "$surface1", bg = "$base",     attrs = "theme_default" }
"mail.listing.compact.even"                       = { fg = "$text",     bg = "$surface0", attrs = "theme_default" }
"mail.listing.compact.odd"                        = { fg = "$text",     bg = "$base",     attrs = "theme_default" }
"mail.listing.compact.even_unseen"                = { fg = "$base",     bg = "$sapphire", attrs = "Bold" }
"mail.listing.compact.odd_unseen"                 = { fg = "$base",     bg = "$sapphire", attrs = "Bold" }
"mail.listing.compact.even_selected"              = { fg = "$base",     bg = "$green",    attrs = "theme_default" }
"mail.listing.compact.odd_selected"               = { fg = "$base",     bg = "$green",    attrs = "theme_default" }
"mail.listing.compact.even_highlighted"           = { fg = "$text",     bg = "$surface1", attrs = "theme_default" }
"mail.listing.compact.odd_highlighted"            = { fg = "$text",     bg = "$surface1", attrs = "theme_default" }
"mail.listing.compact.even_highlighted_selected"  = { fg = "$base",     bg = "$green",    attrs = "Reverse" }
"mail.listing.compact.odd_highlighted_selected"   = { fg = "$base",     bg = "$green",    attrs = "Reverse" }
"mail.listing.conversations"                      = { fg = "$subtext0", bg = "$base",     attrs = "theme_default" }
"mail.listing.conversations.subject"              = { fg = "$text",     bg = "$base",     attrs = "Bold" }
"mail.listing.conversations.from"                 = { fg = "$blue",     bg = "$base",     attrs = "theme_default" }
"mail.listing.conversations.date"                 = { fg = "$mauve",    bg = "$base",     attrs = "theme_default" }
"mail.listing.conversations.unseen"               = { fg = "$base",     bg = "$sapphire", attrs = "Bold" }
"mail.listing.conversations.highlighted"          = { fg = "$text",     bg = "$surface1", attrs = "Bold" }
"mail.listing.conversations.selected"             = { fg = "$base",     bg = "$green",    attrs = "theme_default" }
"mail.listing.conversations.highlighted_selected" = { fg = "$base",     bg = "$green",    attrs = "Reverse" }
"mail.listing.plain.even"                         = { fg = "$text",     bg = "$surface0", attrs = "theme_default" }
"mail.listing.plain.odd"                          = { fg = "$text",     bg = "$base",     attrs = "theme_default" }
"mail.listing.plain.even_unseen"                  = { fg = "$base",     bg = "$sapphire", attrs = "Bold" }
"mail.listing.plain.odd_unseen"                   = { fg = "$base",     bg = "$sapphire", attrs = "Bold" }
"mail.listing.plain.even_selected"                = { fg = "$base",     bg = "$green",    attrs = "theme_default" }
"mail.listing.plain.odd_selected"                 = { fg = "$base",     bg = "$green",    attrs = "theme_default" }
"mail.listing.plain.even_highlighted"             = { fg = "$text",     bg = "$surface1", attrs = "theme_default" }
"mail.listing.plain.odd_highlighted"              = { fg = "$text",     bg = "$surface1", attrs = "theme_default" }
"mail.listing.plain.even_highlighted_selected"    = { fg = "$base",     bg = "$green",    attrs = "Reverse" }
"mail.listing.plain.odd_highlighted_selected"     = { fg = "$base",     bg = "$green",    attrs = "Reverse" }
"mail.view.headers"                               = { fg = "$blue",     bg = "$base",     attrs = "theme_default" }
"mail.view.headers_names"                         = { fg = "$blue",     bg = "$base",     attrs = "Bold" }
"mail.view.headers_area"                          = { fg = "$text",     bg = "$base",     attrs = "theme_default" }
"mail.view.body"                                  = { fg = "$text",     bg = "$base",     attrs = "theme_default" }
"mail.view.thread.indentation.a"                  = { fg = "$base",     bg = "$blue",     attrs = "theme_default" }
"mail.view.thread.indentation.b"                  = { fg = "$base",     bg = "$red",      attrs = "theme_default" }
"mail.view.thread.indentation.c"                  = { fg = "$base",     bg = "$pink",     attrs = "theme_default" }
"mail.view.thread.indentation.d"                  = { fg = "$base",     bg = "$yellow",   attrs = "theme_default" }
"mail.view.thread.indentation.e"                  = { fg = "$base",     bg = "$peach",    attrs = "theme_default" }
"mail.view.thread.indentation.f"                  = { fg = "$base",     bg = "$teal",     attrs = "theme_default" }
"mail.listing.attachment_flag"                    = { fg = "$peach",    bg = "theme_default", attrs = "theme_default" }
"mail.listing.thread_snooze_flag"                 = { fg = "$red",      bg = "theme_default", attrs = "theme_default" }
"mail.listing.tag_default"                        = { fg = "$base",     bg = "$mauve",    attrs = "Bold" }
"mail.listing.highlight_self"                     = { fg = "$lavender", bg = "theme_default", attrs = "theme_default" }
"pager.highlight_search"                          = { fg = "$base",     bg = "$teal",     attrs = "Bold" }
"pager.highlight_search_current"                  = { fg = "$base",     bg = "$blue",     attrs = "Bold" }

# Catppuccin Mocha palette
[terminal.themes.catppuccin-mocha.color_aliases]
"rosewater" = "#f5e0dc"
"flamingo"  = "#f2cdcd"
"pink"      = "#f5c2e7"
"mauve"     = "#cba6f7"
"red"       = "#f38ba8"
"maroon"    = "#eba0ac"
"peach"     = "#fab387"
"yellow"    = "#f9e2af"
"green"     = "#a6e3a1"
"teal"      = "#94e2d5"
"sky"       = "#89dceb"
"sapphire"  = "#74c7ec"
"blue"      = "#89b4fa"
"lavender"  = "#b4befe"
"text"      = "#cdd6f4"
"subtext1"  = "#bac2de"
"subtext0"  = "#a6adc8"
"overlay2"  = "#9399b2"
"overlay1"  = "#7f849c"
"overlay0"  = "#6c7086"
"surface2"  = "#585b70"
"surface1"  = "#45475a"
"surface0"  = "#313244"
"base"      = "#1e1e2e"
"mantle"    = "#181825"
"crust"     = "#11111b"
